### ISSUE TITLE
issue in inserting data

### ISSUE THREAD

**Issue by DesaiSiddhesh1** [p32929/AndroidEasySQL-Library#10]
![Screenshot (46)](https://user-images.githubusercontent.com/101202428/168595636-714b5659-523b-484f-88b4-a0e80c999e41.png)
![Screenshot (47)](https://user-images.githubusercontent.com/101202428/168595647-e4d66ec3-e64c-4565-97ed-1a15e20a3734.png)

**Comment by p32929** [comment]
You tried to add two items with the same values even though you've set it to unique. Change the value & try again :)

**Comment by DesaiSiddhesh1** [comment]
I have not set anything to unique. Please see in first image

**Comment by p32929** [comment]
Can you send me a message in my whatsapp or facebook?
You can find the details here: https://p32929.github.io/
