### ISSUE TITLE
Is there any need of these SDKs in this lib?

### ISSUE THREAD

**Issue by soham24** [p32929/AndroidEasySQL-Library#2]
Due to this, the APK size is increased. Should I remove these dependencies?

    implementation 'com.android.support:appcompat-v7:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

**Comment by p32929** [comment]
Oops! I really forgot to do that. Thanks for pointing it out. I'm gonna update the library with the issue you pointed out soon...

**Comment by p32929** [comment]
Updated the library & also made "minifyEnabled true". Hope, this library won't affect the apk size anymore...

**Comment by p32929** [comment]
Thanks for pointing it out. I'm gonna remove those dependencies and update the library soon

**Comment by p32929** [comment]
Just fixed the issue you pointed out & updated the library to v1.3.10
Please give it a try and let me know if everything's okay :)

**Comment by soham24** [comment]
Thank you so much
