### ISSUE TITLE
How check if data exist?

### ISSUE THREAD

**Issue by UrbanSide** [p32929/AndroidEasySQL-Library#4]
How can I check if there is data in the table so as not to duplicate them?
I am recording data from Firebase realtime DB through your library.
I need that if the user already has a table with data, duplicates are not written.

> Thanks for the answer and your library, it really helped me use SQLite

**Comment by p32929** [comment]
You can achieve this in two ways:
1. By using constrains while initializing the Database and Table. For an Example:
```
EasyDB.init(this, "TEST") // TEST is the name of the DATABASE
                       .setTableName("DEMO TABLE")  // You can ignore this line if you want
                       .addColumn("C1", "text", "unique")
                       .doneTableColumn();
```
So, the column `C1` can never have a duplicate value

2. You can search for a value inside a column using the `searchInColumn` method. Check out the documentation for more info...

And last but not the least thing to let you know, this library has been updated to V2 and it can be found here: https://github.com/p32929/EasiestSqlLibrary
Please, use the updated version from your next project as it has more built in LAZY functions :)
Thanks
